version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - ocramius
  assignees:
  - ocramius
  labels:
  - Enhancement
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: symfony/polyfill-php80
    versions:
    - 1.22.1
